apiVersion: v1
kind: BuildConfig
metadata:
  name: cv-test
spec:
  runPolicy: Serial
  completionDeadlineSeconds: 1800
  source:
    git:
      ref: v0.0.1
      uri: https://github.com/jobtechswe/mydata
    contextDir: examples/cv
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: cv:test
  resources:
    limits:
      memory: 1Gi
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: cv-ci
spec:
  runPolicy: Serial
  completionDeadlineSeconds: 1800
  triggers:
    -
      type: GitHub
      github:
        secretReference:
          name: github-webhook-secret
  source:
    git:
      ref: master
      uri: https://github.com/jobtechswe/mydata
    contextDir: examples/cv
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: cv:latest
  resources:
    limits:
      memory: 1Gi
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: cv-dockerhub
spec:
  runPolicy: Serial
  completionDeadlineSeconds: 1800
  source:
    git:
      ref: master
      uri: https://github.com/jobtechswe/mydata
    contextDir: examples/cv
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: DockerImage
      name: docker.io/jobtechswe/mydata-cv
    pushSecret:
      name: dockerhub
  resources:
    limits:
      memory: 1Gi
