apiVersion: v1
kind: BuildConfig
metadata:
  name: operator-ci
spec:
  runPolicy: Serial
  completionDeadlineSeconds: 1800
  triggers:
    -
      type: GitHub
      github:
        secretReference:
          name: github-webhook-secret
  source:
    git:
      ref: master
      uri: https://github.com/jobtechswe/mydata
    contextDir: operator
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: operator:latest
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: operator-test
spec:
  runPolicy: Serial
  completionDeadlineSeconds: 1800
  source:
    git:
      ref: v0.0.1
      uri: https://github.com/jobtechswe/mydata
    contextDir: operator
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: operator:test
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: operator-dockerhub
spec:
  runPolicy: Serial
  completionDeadlineSeconds: 1800
  source:
    git:
      ref: master
      uri: https://github.com/jobtechswe/mydata
    contextDir: operator
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: DockerImage
      name: docker.io/jobtechswe/mydata-operator
    pushSecret:
      name: dockerhub
